default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project-mod_development

test:
  <<: *default
  database: project-mod_test

production:
  <<: *default
  database: project-mod_production
  username: project-mod
  password: <%= ENV['PROJECT-MOD_DATABASE_PASSWORD'] %>
